import {test,expect} from '@playwright/test';
import {fixtureApi} from './fixture-api';
test('календарь DARAI: выбор даты и времени, клавиатура, отмена',async({page})=>{
 await fixtureApi(page);await page.goto('/');await page.getByLabel('Логин',{exact:true}).fill('fixture-admin');await page.getByLabel('Пароль',{exact:true}).fill('fixture-only-password');await page.getByRole('button',{name:'Войти в рабочее пространство'}).click();await page.getByRole('link',{name:'＋ Создать совещание'}).click();
 const input=page.getByLabel('Дата и время',{exact:true});await input.fill('2026-09-23T17:51');await page.getByRole('button',{name:'Открыть календарь'}).click();const dialog=page.getByRole('dialog',{name:'Выберите дату и время'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'23 сентября 2026 г.',exact:true})).toBeFocused();
 await page.keyboard.press('ArrowRight');await expect(dialog.getByRole('button',{name:'24 сентября 2026 г.',exact:true})).toBeFocused();await dialog.getByLabel('Часы начала').selectOption('09');await dialog.getByLabel('Минуты начала').selectOption('30');await page.screenshot({path:'test-results/darai-calendar.png'});await dialog.getByRole('button',{name:'Выбрать дату'}).click();await expect(input).toHaveValue('2026-09-24T09:30');await expect(page.getByRole('button',{name:'Открыть календарь'})).toBeFocused();
 await page.getByRole('button',{name:'Открыть календарь'}).click();await dialog.getByRole('button',{name:'Следующий месяц'}).click();await expect(dialog.getByText('октябрь 2026 г.',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(input).toHaveValue('2026-09-24T09:30');
 await page.setViewportSize({width:390,height:740});await page.getByRole('button',{name:'Открыть календарь'}).click();const bounds=await dialog.boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390);await page.keyboard.press('Escape');
});
